version: 2.1
orbs:
  node: circleci/node@7.1.0
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the Project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: /home/circleci/project  # Attach workspace at the project root
      - run:
          name: List built files
          command: ls -al /home/circleci/project/dist
      - run:
          name: Deploy to Server
          command: |
            scp -r -v /home/circleci/project/dist/* $SERVER_USER@$SERVER_IP:$SERVER_DIR
            ssh $SERVER_USER@$SERVER_IP "sudo systemctl restart nginx"

workflows:
  build_and_deploy:
    jobs:
      - build-node:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build-node
          filters:
            branches:
              only: master
