version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:lts
    resource_class: medium

jobs:
  build:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pnpm-deps-{{ checksum "pnpm-lock.yaml" }}
            - v1-pnpm-deps-
      - run:
          name: Enable Corepack and Prepare pnpm
          command: |
            corepack enable
            corepack prepare pnpm@latest --activate
            pnpm config set store-dir .pnpm-store
            echo "Using pnpm version: $(pnpm --version)"
      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: v1-pnpm-deps-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  deploy:
    executor: node_executor
    environment:
      PM2_APP_NAME: spencer-frost-portfolio
    steps:
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: List attached workspace files
          command: ls -al /home/circleci/project

      - run:
          name: Deploy Code to Server via Rsync
          command: |
            if ! command -v rsync &> /dev/null; then
              echo "rsync could not be found, installing..."
              sudo apt-get update && sudo apt-get install -y rsync
            fi
            echo "Deploying to $SERVER_IP..."
            rsync -rlvz --delete \
              -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
              --exclude='node_modules' \
              --exclude='.output' \
              /home/circleci/project/ \
              $SERVER_USER@$SERVER_IP:/var/www/spencerfrost

      - run:
          name: Install, Build, Rebuild better-sqlite3, and Reload App
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_USER@$SERVER_IP " \
              cd /var/www/spencerfrost && \
              pnpm install && \
              pnpm run build && \
              pnpm rebuild better-sqlite3 && \
              if [ -f pnpm-workspace.yaml ]; then pnpm approve-builds || true; fi && \
              pm2 reload ecosystem.config.cjs --only $PM2_APP_NAME || pm2 restart ecosystem.config.cjs --only $PM2_APP_NAME \
            "
            echo "Deployment steps complete."

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
